name: QA Tests CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

  schedule:
    - cron: '0 0 * * *' # Every day at midnight UTC
    - cron: '0 12 * * *' # Every day at noon UTC

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Verify test app directory
      run: |
        if [ -d "test-app" ]; then
          echo "Test application directory exists"
          ls -la test-app/
        else
          echo "Error: Test application directory not found"
          exit 1
        fi
    
    - name: Create docker network
      run: docker network create qa-test-network
    
    - name: Start web application
      run: |
        docker run -d --name webapp --network qa-test-network -p 8080:80 -v ${{ github.workspace }}/test-app:/usr/share/nginx/html nginx:alpine
        echo "Web application started at http://localhost:8080"
    
    - name: Build test image
      run: |
        docker build -t qa-tests .
        echo "Test image built successfully"
    
    - name: Run tests
      run: |
        docker run --name test-container --network qa-test-network -e TEST_URL=http://webapp -v ${{ github.workspace }}/reports:/app/reports qa-tests
      continue-on-error: true
    
    - name: Copy test reports
      run: |
        docker cp test-container:/app/report.html ./report.html || echo "No report generated"
    
    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: |
          ./report.html
          ./reports/
        if-no-files-found: warn
    
    - name: Clean up
      if: always()
      run: |
        docker rm -f test-container || true
        docker rm -f webapp || true
        docker network rm qa-test-network || true