name: QA Tests CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Create test app directory
      run: mkdir -p test-app
      
    - name: Copy test app files
      run: |
        if [ -f "test-app/index.html" ]; then
          echo "Test app already exists"
        else
          echo "Creating test app"
          cp -r $(find . -name "test-app-html" | head -1) test-app/index.html || echo "Using default test app"
        fi
    
    - name: Start test environment
      run: |
        docker-compose up -d webapp
        
    - name: Build and run tests
      run: |
        docker build -t qa-tests .
        docker run --name test-container --network=$(docker network ls --filter name=${GITHUB_REPOSITORY_OWNER}-qa-devops -q) -e TEST_URL=http://webapp qa-tests
      
    - name: Copy test reports
      if: always()
      run: |
        docker cp test-container:/app/report.html ./report.html || echo "No report generated"
        
    - name: Upload test report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-report
        path: ./report.html
    
    - name: Clean up
      if: always()
      run: |
        docker rm test-container || true
        docker-compose down